Repository FourierFlows/GeophysicalFlows.jl, pull requests merged in 2020-09, with the labels that each got.

#103 Adds enstrophy budget diagnostics for 2D and barotropic QG
  .gitignore
  examples/twodnavierstokes_stochasticforcing.jl
  src/barotropicqg.jl
  src/twodnavierstokes.jl
  test/runtests.jl
  test/test_twodnavierstokes.jl
Labels: enhancement

#105 Make test_energybudgets great again
  test/test_barotropicqg.jl
  test/test_barotropicqgql.jl
  test/test_twodnavierstokes.jl
Labels: bug, tests

#108 Separate 2D Navier-Stokes stochastic forcing & budgets examples
  docs/make.jl
  examples/barotropicqg_betadecay.jl
  examples/barotropicqg_betaforced.jl
  examples/barotropicqgql_betaforced.jl
  examples/multilayerqg_2layer.jl
  examples/twodnavierstokes_stochasticforcing.jl
  examples/twodnavierstokes_stochasticforcing_budgets.jl
Labels: docs

#111 Adds Surface QG model and example
  docs/make.jl
  docs/src/basics.md
  docs/src/man/functions.md
  docs/src/man/types.md
  docs/src/modules/surfaceqg.md
  examples/surfaceqg_decaying.jl
  src/GeophysicalFlows.jl
  src/surfaceqg.jl
  test/runtests.jl
  test/test_surfaceqg.jl
Labels: enhancement

#118 Updates surfaceqg_decaying.jl example
  examples/surfaceqg_decaying.jl
Labels: docs

#114 Animations in Docs don't show up in Safari
  docs/src/index.md
Labels: docs
