Repository FourierFlows/GeophysicalFlows.jl, pull requests merged in 2020-01, with the labels that each got.

#36 update TwoDTurb docs
  docs/src/modules/twodturb.md
Labels: docs

#43 Reduce dependencies
  .gitignore
  Project.toml
  examples/Project.toml
  examples/README.md
Labels: cleanup

#37 Travis-CI tests use julia v1.3
  .gitlab-ci.yml
  .travis.yml
  Manifest.toml
  appveyor.yml
Labels: tests

#38 GPUify the BarotropicQG module
  .travis.yml
  Project.toml
  src/barotropicqg.jl
  test/runtests.jl
  test/test_barotropicqg.jl
  test/test_twodturb.jl
Labels: GPU
