Repository FourierFlows/GeophysicalFlows.jl, pull requests merged in 2022-12, with the labels that each got.

#314 Add warning for using `MultiLayerQG` with single fluid layer
  src/multilayerqg.jl
Labels: 🚰 user experience

#313 Option to specify topographic PV large-scale gradients in `MultiLayerQG`
  Project.toml
  src/multilayerqg.jl
  test/runtests.jl
  test/test_multilayerqg.jl
Labels: 🤥 enhancement, 🚰 user experience

#316 Faster and with reduced memory allocations `calcF!` function in examples with stochastic noise
  docs/src/visualize.md
  examples/barotropicqgql_betaforced.jl
  examples/singlelayerqg_betaforced.jl
  examples/twodnavierstokes_stochasticforcing.jl
  examples/twodnavierstokes_stochasticforcing_budgets.jl
Labels: optimization 🏎
