Repository FourierFlows/GeophysicalFlows.jl, pull requests merged in 2023-06, with the labels that each got.

#293 Bit of cleanup and using `views` in `MultiLayerQG` module
  .github/workflows/Documenter.yml
  docs/Project.toml
  docs/make.jl
  docs/src/stochastic_forcing.md
  examples/barotropicqgql_betaforced.jl
  examples/multilayerqg_2layer.jl
  examples/singlelayerqg_betadecay.jl
  examples/singlelayerqg_betaforced.jl
  examples/singlelayerqg_decaying_barotropic_equivalentbarotropic.jl
  examples/singlelayerqg_decaying_topography.jl
  examples/surfaceqg_decaying.jl
  examples/twodnavierstokes_decaying.jl
  examples/twodnavierstokes_stochasticforcing.jl
  examples/twodnavierstokes_stochasticforcing_budgets.jl
  src/multilayerqg.jl
  test/test_multilayerqg.jl
  test/test_surfaceqg.jl
  test/test_twodnavierstokes.jl
Labels: 🧹 cleanup

#329 Fixing sign error for mean meridional PV gradient `Qy` in `MultiLayerQG` module
  Project.toml
  src/multilayerqg.jl
  test/runtests.jl
  test/test_multilayerqg.jl
Labels: 🐞 bug

#330 Add Julia v1.9 on CI
  .buildkite/pipeline.yml
  appveyor.yml
Labels: 🪤 tests
