Repository FourierFlows/GeophysicalFlows.jl, pull requests merged in 2023-12, with the labels that each got.

#345 Update Drivas & Elgindi ref
  docs/src/index.md
Labels: 📔 documentation

#346 Bump compat for FourierFlows + CUDA v5
  .buildkite/pipeline.yml
  Project.toml
  appveyor.yml
Labels: 🎮 gpu, 📦 package

#343 Accepting buoyancy instead of density in `MultiLayerQG` module
  Project.toml
  docs/src/index.md
  docs/src/modules/multilayerqg.md
  examples/multilayerqg_2layer.jl
  src/multilayerqg.jl
  test/test_multilayerqg.jl
Labels: 🤥 enhancement, science 🔬
