Repository FourierFlows/GeophysicalFlows.jl, pull requests merged in 2025-01, with the labels that each got.

#377 Simpler default for b in `MultilayerQG`
  src/multilayerqg.jl
Labels: 🧹 cleanup

#373 Accelerating MultiLayerQG on GPUs + remove hardcoded 2-layer implementation
  Project.toml
  docs/src/lib/functions.md
  docs/src/lib/types.md
  examples/multilayerqg_2layer.jl
  src/multilayerqg.jl
Labels: 🎮 gpu, optimization 🏎

#378 Use CairoMakie v0.13 in Docs
  .github/workflows/DocPreviewsCleanup.yml
  Project.toml
  docs/Project.toml
  docs/make.jl
  examples/barotropicqgql_betaforced.jl
  examples/multilayerqg_2layer.jl
  examples/singlelayerqg_betadecay.jl
  examples/singlelayerqg_betaforced.jl
  examples/singlelayerqg_decaying_barotropic_equivalentbarotropic.jl
  examples/singlelayerqg_decaying_topography.jl
  examples/surfaceqg_decaying.jl
  examples/twodnavierstokes_decaying.jl
  examples/twodnavierstokes_stochasticforcing.jl
  examples/twodnavierstokes_stochasticforcing_budgets.jl
Labels: 📔 documentation

#380 Cleanup for `MultilayerQG` fluxes + add test for fluxes with `nlayers=3`
  docs/src/lib/functions.md
  src/multilayerqg.jl
  test/runtests.jl
  test/test_multilayerqg.jl
Labels: 🪤 tests
